sudo: required
services:
  - docker
env:
  global:
    - GIT_SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
  - openssl aes-256-cbc -K $encrypted_0c35eebf403c_key -iv $encrypted_0c35eebf403c_iv -in multi-k8s.json.enc -out multi-k8s.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file multi-k8s.json
  - gcloud config set project multi-k8s-272918
  - gcloud config set compute/zone us-east1-b
  - gcloud container clusters get-credentials multi-cluster
  - echo "$DOCKER_PASSWORD" | docker login -U "$DOCKER_USERNAME" --password-stdin
  # username: theoppermanian
  - docker build -t theoppermanian/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true theoppermanian/react-test npm run test

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
