apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: postgres-persistent-volume-claim
  namespace: k8s
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi


